# **Basic Tensors**

In [1]:
import torch
torch.__version__

'1.13.0+cu116'

In [2]:
import numpy as np
l=[1,2,3,4,5]
arr=np.array(l)
arr.dtype

dtype('int64')

In [4]:
tensor=torch.from_numpy(arr)
tensor.dtype

torch.int64

In [5]:
#Normal indexing as numpy
tensor[2]

tensor(3)

In [6]:
#Disadvantage of numpy: It uses same memory location as numpy and tensor

In [7]:
#To Prevent this using torch.tensor
tensor_arr=torch.tensor(arr)
tensor_arr

tensor([1, 2, 3, 4, 5])

In [8]:
tensor_arr[2]=100
print(tensor_arr)
print(arr)

tensor([  1,   2, 100,   4,   5])
[1 2 3 4 5]


In [10]:
#Zeroes and Ones
torch.zeros(2,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [11]:
torch.ones(2,3,dtype=torch.int64)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
a=torch.tensor(np.arange(0,15).reshape(5,3))

In [18]:
#Indexing
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]])

# **Arithmetic Operation**

In [20]:
a=torch.tensor([3,4,5], dtype=torch.float)
b=torch.tensor([4,5,6], dtype=torch.float)

In [21]:
print(a+b)

tensor([ 7.,  9., 11.])


In [23]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [24]:
c=torch.zeros(3)

In [26]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [27]:
c

tensor([ 7.,  9., 11.])

In [28]:
torch.add(a,b).sum()

tensor(27.)

# **Dot Product and Multi Operations**

In [29]:
x=torch.tensor([3,4,5], dtype=torch.float)
y=torch.tensor([4,5,6], dtype=torch.float)

In [30]:
x.mul(y)

tensor([12., 20., 30.])

In [31]:
x.dot(y)

tensor(62.)

In [33]:
#Matix Multiplication
x=torch.tensor([[3,4,5],[1,2,2]], dtype=torch.float)
y=torch.tensor([[4,5],[3,2], [2,1]], dtype=torch.float)

In [34]:
torch.matmul(x,y)

tensor([[34., 28.],
        [14., 11.]])

In [36]:
torch.mm(x,y)

tensor([[34., 28.],
        [14., 11.]])

In [37]:
x@y

tensor([[34., 28.],
        [14., 11.]])

# **Back Propagation Using Pytorch**

- To Compute Derivatives


In [38]:
import torch
#require_grads parameter should be set to True to perform the backpropogation in Torch
x=torch.tensor(4.0, requires_grad=True)

In [39]:
x

tensor(4., requires_grad=True)

In [40]:
y=x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [41]:
#Back Propogation
'''
backward() is used to compute the gradient of current tensor
'''
y.backward()

In [42]:
print(x.grad)

tensor(8.)


In [43]:
l=[[2.0,1.0,2.0],[3.0,2.0,1.0],[2.0,4.0,1.0]]
torch_input=torch.tensor(l, requires_grad=True)

In [44]:
torch_input

tensor([[2., 1., 2.],
        [3., 2., 1.],
        [2., 4., 1.]], requires_grad=True)

In [54]:
# y=x**3+x**2
y=torch_input**3+torch_input**2

In [55]:
y

tensor([[12.,  2., 12.],
        [36., 12.,  2.],
        [12., 80.,  2.]], grad_fn=<AddBackward0>)

In [56]:
z=y.sum()

In [57]:
z

tensor(170., grad_fn=<SumBackward0>)

In [58]:
z.backward()
#y=3x**2+2x

In [59]:
torch_input.grad

tensor([[ 32.,  10.,  32.],
        [ 66.,  32.,  10.],
        [ 32., 112.,  10.]])