# **House Price Prediction**

In [34]:
import numpy as np
import pandas as pd
import plotly.express as px
import seaborn as sns

In [35]:
df=pd.read_csv('housepricedataset.csv', usecols=["SalePrice", "MSSubClass", "MSZoning", "LotFrontage", "LotArea", "Street", "YearBuilt", "LotShape", "1stFlrSF", "2ndFlrSF"]).dropna()

In [36]:
df.shape

(1201, 10)

In [37]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   
3          70       RL         60.0     9550   Pave      IR1       1915   
4          60       RL         84.0    14260   Pave      IR1       2000   

   1stFlrSF  2ndFlrSF  SalePrice  
0       856       854     208500  
1      1262         0     181500  
2       920       866     223500  
3       961       756     140000  
4      1145      1053     250000

In [38]:
df.tail(10
)

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
1450          90       RL         60.0     9000   Pave      Reg       1974   
1451          20       RL         78.0     9262   Pave      Reg       2008   
1452         180       RM         35.0     3675   Pave      Reg       2005   
1453          20       RL         90.0    17217   Pave      Reg       2006   
1454          20       FV         62.0     7500   Pave      Reg       2004   
1455          60       RL         62.0     7917   Pave      Reg       1999   
1456          20       RL         85.0    13175   Pave      Reg       1978   
1457          70       RL         66.0     9042   Pave      Reg       1941   
1458          20       RL         68.0     9717   Pave      Reg       1950   
1459          20       RL         75.0     9937   Pave      Reg       1965   

      1stFlrSF  2ndFlrSF  SalePrice  
1450       896       896     136000  
1451      1578         0     287090  
1452      1072         0     145000  
1453      1140         0      84500  
1454      1221         0     185000  
1455       953       694     175000  
1456      2073         0     210000  
1457      1188      1152     266500  
1458      1078         0     142125  
1459      1256         0     147500

In [39]:
df.describe()

MSSubClass  LotFrontage        LotArea    YearBuilt     1stFlrSF  \
count  1201.000000  1201.000000    1201.000000  1201.000000  1201.000000   
mean     57.198168    70.049958    9951.698585  1970.580350  1158.437968   
std      43.106427    24.284752    7924.353975    31.750335   386.257235   
min      20.000000    21.000000    1300.000000  1872.000000   334.000000   
25%      20.000000    59.000000    7420.000000  1950.000000   876.000000   
50%      50.000000    69.000000    9262.000000  1972.000000  1082.000000   
75%      70.000000    80.000000   11249.000000  2003.000000  1383.000000   
max     190.000000   313.000000  215245.000000  2010.000000  4692.000000   

          2ndFlrSF      SalePrice  
count  1201.000000    1201.000000  
mean    346.073272  180770.480433  
std     435.143451   83389.519866  
min       0.000000   34900.000000  
25%       0.000000  127500.000000  
50%       0.000000  159500.000000  
75%     728.000000  213500.000000  
max    2065.000000  755000.000000

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   object 
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   object 
 5   LotShape     1201 non-null   object 
 6   YearBuilt    1201 non-null   int64  
 7   1stFlrSF     1201 non-null   int64  
 8   2ndFlrSF     1201 non-null   int64  
 9   SalePrice    1201 non-null   int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 103.2+ KB


In [41]:
for i in df.columns:
  print(f"Column {i}  unique values : {len(df[i].unique())}")

Column MSSubClass  unique values : 15
Column MSZoning  unique values : 5
Column LotFrontage  unique values : 110
Column LotArea  unique values : 869
Column Street  unique values : 2
Column LotShape  unique values : 4
Column YearBuilt  unique values : 112
Column 1stFlrSF  unique values : 678
Column 2ndFlrSF  unique values : 368
Column SalePrice  unique values : 597


In [42]:
import datetime
curr=datetime.datetime.now().year
curr

2022

In [43]:
#To find the difference in the year as year built would not be affective
df["Total_years"]= curr-df["YearBuilt"]
df.drop("YearBuilt", axis=1, inplace=True)

In [44]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  1stFlrSF  \
0          60       RL         65.0     8450   Pave      Reg       856   
1          20       RL         80.0     9600   Pave      Reg      1262   
2          60       RL         68.0    11250   Pave      IR1       920   
3          70       RL         60.0     9550   Pave      IR1       961   
4          60       RL         84.0    14260   Pave      IR1      1145   

   2ndFlrSF  SalePrice  Total_years  
0       854     208500           19  
1         0     181500           46  
2       866     223500           21  
3       756     140000          107  
4      1053     250000           22

In [45]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', '1stFlrSF', '2ndFlrSF', 'SalePrice', 'Total_years'],
      dtype='object')

In [46]:
categorical=['MSSubClass', 'MSZoning', 'Street',
       'LotShape']

In [47]:
out="SalePrice"

In [48]:
#Label Encoding
from sklearn.preprocessing import LabelEncoder
label={}
label["MSSubClass"]=LabelEncoder()
label["MSSubClass"].fit_transform(df["MSSubClass"])

array([5, 0, 5, ..., 6, 0, 0])

In [49]:
label

{'MSSubClass': LabelEncoder()}

In [50]:
from sklearn.preprocessing import LabelEncoder
label={}
for f in categorical:
  label[f]=LabelEncoder()
  df[f]=label[f].fit_transform(df[f])

In [51]:
df.head()

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  1stFlrSF  \
0           5         3         65.0     8450       1         3       856   
1           0         3         80.0     9600       1         3      1262   
2           5         3         68.0    11250       1         0       920   
3           6         3         60.0     9550       1         0       961   
4           5         3         84.0    14260       1         0      1145   

   2ndFlrSF  SalePrice  Total_years  
0       854     208500           19  
1         0     181500           46  
2       866     223500           21  
3       756     140000          107  
4      1053     250000           22

In [52]:
'''
To Take all categorical features and convert into numpy and then torch with the help
of Embedding layers
'''
#Categorical features into numpy
cat_f=np.stack([df["MSSubClass"], df["MSZoning"], df["Street"], df["LotShape"]], 1)
cat_f

array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]])

In [53]:
#Converting Numpy to Tensors
#Categorical features should not be converted into float data type
import torch
cat_f=torch.tensor(cat_f, dtype=torch.int64)
cat_f

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [54]:
# Create Continuous Variable (To take continuous value)
cont_f=[]
for i in df.columns:
    if i in ["MSSubClass", "MSZoning", "Street", "LotShape","SalePrice"]:
        pass
    else:
        cont_f.append(i)

In [55]:
cont_f

['LotFrontage', 'LotArea', '1stFlrSF', '2ndFlrSF', 'Total_years']

In [56]:
#Continuous varibale to numpy--->Torch---->Tensors
#Continuous value can be converted to float
cont_values=np.stack([df[i].values for i in cont_f],axis=1)
cont_values=torch.tensor(cont_values,dtype=torch.float)
cont_values


tensor([[   65.,  8450.,   856.,   854.,    19.],
        [   80.,  9600.,  1262.,     0.,    46.],
        [   68., 11250.,   920.,   866.,    21.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    81.],
        [   68.,  9717.,  1078.,     0.,    72.],
        [   75.,  9937.,  1256.,     0.,    57.]])

In [57]:
cont_values.dtype

torch.float32

In [58]:
#Dependent Feature 
y=torch.tensor(df['SalePrice'].values,dtype=torch.float).reshape(-1,1)
y

tensor([[208500.],
        [181500.],
        [223500.],
        ...,
        [266500.],
        [142125.],
        [147500.]])

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   int64  
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   int64  
 5   LotShape     1201 non-null   int64  
 6   1stFlrSF     1201 non-null   int64  
 7   2ndFlrSF     1201 non-null   int64  
 8   SalePrice    1201 non-null   int64  
 9   Total_years  1201 non-null   int64  
dtypes: float64(1), int64(9)
memory usage: 103.2 KB


In [60]:
cat_f.shape, cont_values.shape, y.shape

(torch.Size([1201, 4]), torch.Size([1201, 5]), torch.Size([1201, 1]))

In [61]:
#Embedding size for categorical columns
len(df['MSSubClass'].unique())

15

In [62]:
#Embedding Size for Categorical Columns
cat_dims=[len(df[col].unique()) for col in ["MSSubClass", "MSZoning", "Street", "LotShape"]]

In [63]:
#Input Dimension
cat_dims

[15, 5, 2, 4]

In [66]:
#Output Dimension should be setbased on the input dimension (min(50, feature dimension/2))
#Not more than 50
embedding_dim=[(x,min(50,(x+1)//2))for x in cat_dims]

In [70]:
# Preporcessing Step
embedding_dim

[(15, 8), (5, 3), (2, 1), (4, 2)]

In [68]:
import torch
import torch.nn as nn
import torch.nn.functional as f
embed_r=nn.ModuleList([nn.Embedding(inp, out) for inp,out in embedding_dim])
#For Multiple embedding list Module List

In [69]:
embed_r

ModuleList(
  (0): Embedding(15, 8)
  (1): Embedding(5, 3)
  (2): Embedding(2, 1)
  (3): Embedding(4, 2)
)

In [71]:
cat_f

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [73]:
cat_fz=cat_f[:4]
cat_fz

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        [6, 3, 1, 0]])